model_params:
  name: "faster-rcnn"
  num_classes: 3

optimizer_params:
  learning_rate: 0.001
  weight_decay: 0.001

scheduler_params:
    step:
      size: 1
      gamma: 0.001
    warmup:
      factor: 0.001
      iterations: 100

trainer_params:
  max_epochs: 300